import React, { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { instancesApi } from '../lib/api';
import { POSTGRES_TYPES } from '../lib/constants';
import { Plus, X, Trash2, Loader2, Save } from 'lucide-react';
import { toast } from 'sonner';

interface CreateTableModalProps {
  instanceName: string;
  onClose: () => void;
  onSuccess: () => void;
}

interface Column {
  name: string;
  type: string;
  isPrimary: boolean;
  isNullable: boolean;
  defaultValue: string;
}

export default function CreateTableModal({ instanceName, onClose, onSuccess }: CreateTableModalProps) {
  const queryClient = useQueryClient();
  const [tableName, setTableName] = useState('');
  const [columns, setColumns] = useState<Column[]>([
    { name: 'id', type: 'int8', isPrimary: true, isNullable: false, defaultValue: 'gen_random_uuid()' }, // Actually int8 auto-increment is common? Or uuid? Supabase default is int8 usually for quickstart or uuid. Let's start with int8 identity.
  ]);

  // Better default: id bigint generated by default as identity primary key
  // But simplified for UI:
  const [useIdentity] = useState(true); // For ID column

  const addColumn = () => {
    setColumns([...columns, { name: '', type: 'text', isPrimary: false, isNullable: true, defaultValue: '' }]);
  };

  const removeColumn = (index: number) => {
    if (columns.length <= 1) return;
    setColumns(columns.filter((_, i) => i !== index));
  };

  const updateColumn = (index: number, field: keyof Column, value: any) => {
    const newColumns = [...columns];
    newColumns[index] = { ...newColumns[index], [field]: value };
    setColumns(newColumns);
  };

  const createTableMutation = useMutation({
    mutationFn: (sql: string) => instancesApi.executeSQL(instanceName, sql),
    onSuccess: (data) => {
      if (data.error) {
        toast.error('Failed to create table', { description: data.error });
      } else {
        toast.success(`Table ${tableName} created`);
        queryClient.invalidateQueries({ queryKey: ['instance-schema', instanceName] });
        onSuccess();
        onClose();
      }
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to create table');
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!tableName.trim()) {
      toast.error('Table name is required');
      return;
    }

    // simplistic SQL generation
    const colDefs = columns.map((col) => {
      let def = `${col.name} ${col.type}`;
      if (col.isPrimary) {
        def += ' PRIMARY KEY';
        if (col.type === 'int8' && useIdentity && col.name === 'id') {
          def += ' GENERATED BY DEFAULT AS IDENTITY';
        }
      }
      if (!col.isNullable && !col.isPrimary) def += ' NOT NULL';
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      return def;
    });

    const sql = `CREATE TABLE public.${tableName} (\n  ${colDefs.join(',\n  ')}\n);`;

    // Also enable RLS by default for security? Supabase does that.
    // sql += `\nALTER TABLE public.${tableName} ENABLE ROW LEVEL SECURITY;`;

    createTableMutation.mutate(sql);
  };

  return (
    <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm'>
      <div className='glass-modal w-full max-w-3xl max-h-[90vh] flex flex-col'>
        <div className='flex items-center justify-between p-6 border-b border-border'>
          <h2 className='text-xl font-semibold'>Create New Table</h2>
          <button onClick={onClose} className='text-muted-foreground hover:text-foreground'>
            <X className='w-5 h-5' />
          </button>
        </div>

        <div className='p-6 overflow-y-auto flex-1'>
          <div className='space-y-6'>
            {/* Table Name */}
            <div>
              <label className='block text-sm font-medium mb-2'>Name</label>
              <input
                type='text'
                value={tableName}
                onChange={(e) => setTableName(e.target.value)}
                placeholder='e.g. users, posts'
                className='w-full px-4 py-2 bg-background border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/50'
              />
            </div>

            {/* Columns */}
            <div>
              <div className='flex items-center justify-between mb-4'>
                <label className='text-sm font-medium'>Columns</label>
                <button onClick={addColumn} className='text-sm flex items-center gap-1 text-primary hover:underline'>
                  <Plus className='w-4 h-4' />
                  Add Column
                </button>
              </div>

              <div className='space-y-3'>
                {columns.map((col, index) => (
                  <div key={index} className='flex gap-3 items-start p-3 bg-secondary/20 rounded-lg'>
                    <div className='flex-1'>
                      <input
                        type='text'
                        value={col.name}
                        onChange={(e) => updateColumn(index, 'name', e.target.value)}
                        placeholder='Column Name'
                        className='w-full px-3 py-2 bg-background border border-border rounded-md text-sm'
                      />
                    </div>
                    <div className='w-32'>
                      <select
                        value={col.type}
                        onChange={(e) => updateColumn(index, 'type', e.target.value)}
                        className='w-full px-3 py-2 bg-background border border-border rounded-md text-sm'
                      >
                        {POSTGRES_TYPES.map((type) => (
                          <option key={type.value} value={type.value} title={type.description}>
                            {type.label}
                          </option>
                        ))}
                      </select>
                    </div>
                    <div className='flex items-center gap-3 pt-2'>
                      <label className='flex items-center gap-1 text-xs cursor-pointer'>
                        <input
                          type='checkbox'
                          checked={col.isPrimary}
                          onChange={(e) => updateColumn(index, 'isPrimary', e.target.checked)}
                          className='rounded border-muted'
                        />
                        Primary
                      </label>
                      <label className='flex items-center gap-1 text-xs cursor-pointer'>
                        <input
                          type='checkbox'
                          checked={col.isNullable}
                          onChange={(e) => updateColumn(index, 'isNullable', e.target.checked)}
                          className='rounded border-muted'
                        />
                        Nullable
                      </label>
                    </div>
                    {columns.length > 1 && (
                      <button
                        onClick={() => removeColumn(index)}
                        className='p-2 text-muted-foreground hover:text-destructive transition-colors'
                      >
                        <Trash2 className='w-4 h-4' />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className='p-6 border-t border-border flex justify-end gap-3'>
          <button
            onClick={onClose}
            className='px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors'
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={createTableMutation.isPending || !tableName}
            className='flex items-center gap-2 px-6 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50'
          >
            {createTableMutation.isPending ? (
              <Loader2 className='w-4 h-4 animate-spin' />
            ) : (
              <Save className='w-4 h-4' />
            )}
            Create Table
          </button>
        </div>
      </div>
    </div>
  );
}
